apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoyproxy
  namespace: envoy-gateway-system
spec:
  type: "oci"
  interval: 5m
  url: oci://docker.io/envoyproxy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  serviceAccountName: flux
  targetNamespace: envoy-gateway-system
  interval: 30m
  chart:
    spec:
      chart: gateway-helm
      version: "1.6.x"
      sourceRef:
        kind: HelmRepository
        name: envoyproxy
      interval: 12h
  releaseName: envoy-gateway
  # https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/values.tmpl.yaml
  values:
    kubernetesClusterDomain: ${CLUSTER_DOMAIN}
