apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-gateway-certificate
  namespace: envoy-gateway-system
spec:
  issuerRef:
    name: vault-gateway-issuer
    kind: ClusterIssuer
  secretName: gateway-tls-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: "*.ilysium.io"
  dnsNames:
    - "*.ilysium.io"
  usages:
    - server auth
    - client auth
