apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: perimeter-envoy-proxy
  namespace: gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        labels:
          networking.ilysium.io/lb-pool: perimeter
      envoyDeployment:
        replicas: 2
